export const farmingCategories = [
  'Crop Farming',
  'Livestock Farming',
  'Aquaculture (Fish Farming)',
  'Poultry Farming',
  'Dairy Farming',
  'Beekeeping (Apiculture)',
  'Sericulture (Silk Farming)',
  'Horticulture (Fruits, Vegetables, and Flowers)',
  'Organic Farming',
  'Hydroponics and Aquaponics',
  'Agroforestry (Integrating Trees and Shrubs with Crops/Livestock)',
  'Viticulture (Grape Farming for Wine)',
  'Floriculture (Flower Farming)',
  'Medicinal and Aromatic Plant Farming',
  'Mushroom Farming',
  'Snail Farming (Heliciculture)',
  'Rabbit Farming (Cuniculture)',
  'Algae Farming',
  'Worm Farming (Vermiculture)',
  'Pasture Farming (Grassland Farming for Grazing Animals)',
  'Integrated Farming (Combining Multiple Farming Systems)',
  'Urban Farming',
  'Vertical Farming',
  'Seed Farming',
  'Agave Farming (For Tequila and Fiber)',
  'Coffee Farming',
  'Tea Farming',
  'Cocoa Farming',
  'Spice Farming',
  'Oilseed Farming (e.g., Sunflower, Soybean, Canola)',
  'Fiber Farming (e.g., Cotton, Jute, Hemp)',
  'Truffle Farming',
  'Oyster Farming',
  'Seaweed Farming',
  'Game Farming (Wildlife Ranching)',
  'Quail Farming',
  'Goat Farming',
  'Sheep Farming',
  'Pig Farming',
  'Deer Farming',
  'Alpaca and Llama Farming',
  'Camel Farming',
  'Ostrich Farming',
  'Fish Farming (Specific Types: Tilapia, Catfish, Salmon, etc.)',
  'Shrimp Farming',
  'Crab Farming',
  'Lobster Farming',
  'Pearl Farming',
  'Ornamental Fish Farming',
  'Saffron Farming',
];
